[workspace]
authors = ["Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>"]
channels = ["conda-forge"]
name = "hello-r-markdown"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup = "Rscript -e 'library(tinytex); tinytex::install_tinytex()'"
pdf = "Rscript -e 'library(rmarkdown); render(\"src/main.Rmd\", output_dir = \"dist\")'"
html = "Rscript -e 'library(rmarkdown); render(\"src/main.Rmd\", output_format = \"html_notebook\", output_dir = \"dist\")' && mv dist/main.nb.html dist/index.html"
clean = "rm -rf dist"

[dependencies]
r = ">=4.5,<4.6"
r-rmarkdown = ">=2.30,<3"
r-tinytex = ">=0.58,<0.59"
r-bookdown = ">=0.46,<0.47"
