name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# Makes the document have the correct timestamp.
env:
  TZ: 'America/Sao_Paulo'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  ci:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install pixi
      uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7
      with:
        pixi-version: v0.61.0
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    - name: Cache tinytex
      id: cache-tinytex
      uses: actions/cache@640a1c2554105b57832a23eea0b4672fc7a790d5
      with:
        path: /home/runner/.TinyTeX
        key: ${{ runner.os }}-tinytex
    - name: Setup tinytex
      if: ${{ steps.cache-tinytex.outputs.cache-hit != 'true' }}
      run: pixi run setup
    - name: Compile PDF
      run: pixi run pdf
    - name: Upload Artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      with:
        name: dist
        path: dist/main.pdf
    - name: Compile HTML
      run: pixi run html
    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b
    - name: Upload Page
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
      with:
        path: dist
    - name: Deploy Page
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
